# Generated by Django 4.2.7 on 2024-04-05 05:05

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("todo_main", "0002_alter_todo_tags_tag_id_alter_todo_tags_todo_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo_tags",
            name="tag_id",
        ),
        migrations.RemoveField(
            model_name="todo_tags",
            name="todo_id",
        ),
        migrations.AddField(
            model_name="todo",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.DeleteModel(
            name="tag",
        ),
        migrations.DeleteModel(
            name="todo_tags",
        ),
    ]
