# This workflow will install Python dependencies, run tests
name: Tests Before Commit

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

# on:
#   schedule:
#     - cron:  '*/15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions

        ports:
          - 5432:5432

        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.2
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8
    - name: Lint with black
      run: |
        pip install black
        black .
    -name: Make Migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate
    - name: Coverage report
      env:
        DB_ENGINE : ${{ secrets.DB_ENGINE }}
        DB_NAME : ${{ secrets.DB_NAME }}
        DB_USER : ${{ secrets.DB_USER }}
        DB_PASSWORD : ${{ secrets.DB_PASSWORD }}
        DB_HOST : ${{ secrets.DB_HOST }}
        DB_PORT : ${{ secrets.DB_PORT }}
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report
    - name: Django Testing
      run: |
        python3 manage.py test
