# This workflow will install Python dependencies, run tests
name: Tests Before Commit

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

# on:
#   schedule:
#     - cron:  '*/15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.11.4
        env:
          MYSQL_USER: demo
          MYSQL_PASSWORD: demo123
          MYSQL_DATABASE: git_actions
          MYSQL_ROOT_PASSWORD: Test@123
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3 

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.2
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.2
    - name : Install maria depenencies
      run : sudo apt-get install python3-dev libmariadb3 libmariadb-dev build-essential pkg-config
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8
    - name: Lint with black
      run: |
        pip install black
        black .
    - name: Coverage report
      env:
        DB_ENGINE : ${{ secrets.DB_ENGINE }}
        DB_NAME : ${{ secrets.DB_NAME }}
        DB_USER : ${{ secrets.DB_USER }}
        DB_PASSWORD : ${{ secrets.DB_PASSWORD }}
        DB_HOST : ${{ secrets.DB_HOST }}
        DB_PORT : ${{ secrets.DB_PORT }}
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report
    - name: Django Testing
      run: |
        python3 manage.py test